# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# --- Safety: disable shrinking and optimization for now ---
# R8 only performs obfuscation (class/method renaming).
# Remove these flags once per-module keep rules are audited and tested.
-dontshrink
-dontoptimize

# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }

# Datadog RUM SDK — keep classes from being shrunk/renamed so the native
# bridge and event mappers resolve correctly once -dontshrink is removed.
-keep class com.datadog.** { *; }
-keep class com.datadog.android.** { *; }
-keep class com.datadog.reactnative.** { *; }

# Suppress R8 warnings for classes not available on Android.
# Generated by R8's missing_rules.txt from a local build.
# These are desktop/server Java APIs referenced by cross-platform libraries
# but never called at runtime on Android.
# TODO: Re-evaluate once -dontshrink is removed. Shrinking may eliminate
# many of these references; re-run the build and update based on missing_rules.txt.
-dontwarn coil3.PlatformContext
-dontwarn com.google.api.client.http.GenericUrl
-dontwarn com.google.api.client.http.HttpHeaders
-dontwarn com.google.api.client.http.HttpRequest
-dontwarn com.google.api.client.http.HttpRequestFactory
-dontwarn com.google.api.client.http.HttpResponse
-dontwarn com.google.api.client.http.HttpTransport
-dontwarn com.google.api.client.http.javanet.NetHttpTransport$Builder
-dontwarn com.google.api.client.http.javanet.NetHttpTransport
# Firebase KTX is pulled transitively by expo-notifications for Android FCM v1.
# Keep this aligned with the Firebase dependency comment in android/app/build.gradle.
-dontwarn com.google.firebase.ktx.Firebase
-dontwarn java.applet.Applet
-dontwarn javax.sound.sampled.AudioFormat
-dontwarn javax.sound.sampled.AudioSystem
-dontwarn javax.sound.sampled.DataLine$Info
-dontwarn javax.sound.sampled.Line$Info
-dontwarn javax.sound.sampled.Line
-dontwarn javax.sound.sampled.LineUnavailableException
-dontwarn javax.sound.sampled.SourceDataLine
-dontwarn org.joda.time.Instant

# Add any project specific keep options here:

# MainApplication enables Fabric feature flags through the JVM-public but
# Kotlin-internal loadWithFeatureFlags entry point via reflection; keep it.
-keepclassmembers class com.facebook.react.defaults.DefaultNewArchitectureEntryPoint {
    *** loadWithFeatureFlags*(...);
}
