import { MWPWalletType } from 'farcaster-expo';
import {
  apeChain,
  arbitrum,
  avalanche,
  base,
  berachain,
  blast,
  bsc,
  celo,
  degen,
  fantom,
  gnosis,
  gravity,
  ink,
  mainnet,
  monadTestnet,
  optimism,
  polygon,
  sanko,
  unichain,
  zetachain,
  zora,
} from 'viem/chains';

export const supportedNetworkIds: Record<MWPWalletType, number[]> = {
  coinbase: [
    mainnet.id,
    arbitrum.id,
    avalanche.id,
    base.id,
    bsc.id,
    celo.id,
    fantom.id,
    gnosis.id,
    optimism.id,
    polygon.id,
    zetachain.id,
    zora.id,
  ],
  rainbow: [
    mainnet.id,
    base.id,
    optimism.id,
    arbitrum.id,
    zora.id,
    blast.id,
    apeChain.id,
    polygon.id,
    avalanche.id,
    celo.id,
    degen.id,
    ink.id,
    sanko.id,
    gravity.id,
    berachain.id,
    bsc.id,
    unichain.id,
    monadTestnet.id,
  ],
};
