// Hermes and some Android WebViews expose Intl.DisplayNames without full ICU
// data, so language codes can echo back unchanged. Keep a static fallback map.
const LANGUAGE_DISPLAY_NAMES: Record<string, string> = {
  afr: 'Afrikaans',
  af: 'Afrikaans',
  alb: 'Albanian',
  am: 'Amharic',
  amh: 'Amharic',
  ar: 'Arabic',
  ara: 'Arabic',
  arm: 'Armenian',
  az: 'Azerbaijani',
  baq: 'Basque',
  be: 'Belarusian',
  ben: 'Bangla',
  bg: 'Bulgarian',
  bn: 'Bangla',
  bod: 'Tibetan',
  bos: 'Bosnian',
  bs: 'Bosnian',
  bul: 'Bulgarian',
  bur: 'Burmese',
  ca: 'Catalan',
  cat: 'Catalan',
  ces: 'Czech',
  chi: 'Chinese',
  cs: 'Czech',
  cze: 'Czech',
  cy: 'Welsh',
  cym: 'Welsh',
  da: 'Danish',
  dan: 'Danish',
  de: 'German',
  deu: 'German',
  el: 'Greek',
  ell: 'Greek',
  en: 'English',
  eng: 'English',
  es: 'Spanish',
  est: 'Estonian',
  et: 'Estonian',
  eu: 'Basque',
  eus: 'Basque',
  fa: 'Persian',
  fas: 'Persian',
  fi: 'Finnish',
  fil: 'Filipino',
  fin: 'Finnish',
  fr: 'French',
  fra: 'French',
  fre: 'French',
  ga: 'Irish',
  geo: 'Georgian',
  ger: 'German',
  gle: 'Irish',
  gl: 'Galician',
  glg: 'Galician',
  gre: 'Greek',
  gu: 'Gujarati',
  guj: 'Gujarati',
  hau: 'Hausa',
  he: 'Hebrew',
  heb: 'Hebrew',
  hi: 'Hindi',
  hin: 'Hindi',
  hr: 'Croatian',
  hrv: 'Croatian',
  hu: 'Hungarian',
  hy: 'Armenian',
  hye: 'Armenian',
  ibo: 'Igbo',
  ice: 'Icelandic',
  id: 'Indonesian',
  ind: 'Indonesian',
  is: 'Icelandic',
  isl: 'Icelandic',
  it: 'Italian',
  ja: 'Japanese',
  jpn: 'Japanese',
  ka: 'Georgian',
  kan: 'Kannada',
  kat: 'Georgian',
  kaz: 'Kazakh',
  kk: 'Kazakh',
  khm: 'Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  kor: 'Korean',
  kur: 'Kurdish',
  ky: 'Kyrgyz',
  lao: 'Lao',
  lat: 'Latin',
  lav: 'Latvian',
  lo: 'Lao',
  lt: 'Lithuanian',
  lit: 'Lithuanian',
  lv: 'Latvian',
  mac: 'Macedonian',
  mal: 'Malayalam',
  mar: 'Marathi',
  may: 'Malay',
  mk: 'Macedonian',
  mkd: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mon: 'Mongolian',
  mr: 'Marathi',
  ms: 'Malay',
  msa: 'Malay',
  mt: 'Maltese',
  my: 'Burmese',
  mya: 'Burmese',
  ne: 'Nepali',
  nep: 'Nepali',
  nl: 'Dutch',
  nld: 'Dutch',
  no: 'Norwegian',
  nor: 'Norwegian',
  pa: 'Punjabi',
  pan: 'Punjabi',
  per: 'Persian',
  pl: 'Polish',
  pol: 'Polish',
  por: 'Portuguese',
  pt: 'Portuguese',
  pus: 'Pashto',
  ro: 'Romanian',
  ron: 'Romanian',
  ru: 'Russian',
  rum: 'Romanian',
  rus: 'Russian',
  si: 'Sinhala',
  sin: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  slk: 'Slovak',
  slo: 'Slovak',
  slv: 'Slovenian',
  spa: 'Spanish',
  sq: 'Albanian',
  sqi: 'Albanian',
  sr: 'Serbian',
  srp: 'Serbian',
  sv: 'Swedish',
  sw: 'Swahili',
  swa: 'Swahili',
  swe: 'Swedish',
  ta: 'Tamil',
  tam: 'Tamil',
  te: 'Telugu',
  tel: 'Telugu',
  tgl: 'Filipino',
  th: 'Thai',
  tha: 'Thai',
  tib: 'Tibetan',
  tl: 'Filipino',
  tr: 'Turkish',
  tur: 'Turkish',
  uk: 'Ukrainian',
  ukr: 'Ukrainian',
  ur: 'Urdu',
  urd: 'Urdu',
  uz: 'Uzbek',
  uzb: 'Uzbek',
  vi: 'Vietnamese',
  vie: 'Vietnamese',
  wel: 'Welsh',
  yor: 'Yoruba',
  zh: 'Chinese',
  zho: 'Chinese',
  zu: 'Zulu',
};

const normalizeLanguageIsoCode = (languageIsoCode: string) => {
  return languageIsoCode.trim().toLowerCase().split(/[-_]/)[0];
};

const getLanguageDisplayNameFallback = (
  languageIsoCode: string | undefined,
) => {
  if (!languageIsoCode) {
    return undefined;
  }

  return LANGUAGE_DISPLAY_NAMES[normalizeLanguageIsoCode(languageIsoCode)];
};

export {
  getLanguageDisplayNameFallback,
  LANGUAGE_DISPLAY_NAMES,
  normalizeLanguageIsoCode,
};
